// <auto-generated />
using IncomeTaxCalculator.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncomeTaxCalculator.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230804191506_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IncomeTaxCalculator.Domain.Entities.TaxResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualTaxPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossAnnualSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossMonthlySalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyTaxPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetAnnualSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetMonthlySalary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TaxResults");
                });
#pragma warning restore 612, 618
        }
    }
}
